apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.chunkLocation.name }}
  namespace: {{ include "cse474.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.chunkLocation.name }}
    {{- include "cse474.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.chunkLocation.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.chunkLocation.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.chunkLocation.name }}
        app.kubernetes.io/name: {{ .Values.services.chunkLocation.name }}
    spec:
      containers:
        - name: {{ .Values.services.chunkLocation.name }}
          image: "{{ .Values.services.chunkLocation.image.repository }}:{{ .Values.services.chunkLocation.image.tag }}"
          imagePullPolicy: {{ .Values.services.chunkLocation.image.pullPolicy }}
          command:
            {{- toYaml .Values.services.chunkLocation.command | nindent 12 }}
          ports:
            - containerPort: {{ .Values.services.chunkLocation.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.services.chunkLocation.name }}-config
            - secretRef:
                name: {{ .Values.services.chunkLocation.name }}-secret
          resources:
            {{- toYaml .Values.services.chunkLocation.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: {{ .Values.services.chunkLocation.probes.startup.path }}
              port: {{ .Values.services.chunkLocation.containerPort }}
            periodSeconds: {{ .Values.services.chunkLocation.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.services.chunkLocation.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.services.chunkLocation.probes.readiness.path }}
              port: {{ .Values.services.chunkLocation.containerPort }}
            initialDelaySeconds: {{ .Values.services.chunkLocation.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.chunkLocation.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.services.chunkLocation.probes.liveness.path }}
              port: {{ .Values.services.chunkLocation.containerPort }}
            initialDelaySeconds: {{ .Values.services.chunkLocation.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.chunkLocation.probes.liveness.periodSeconds }}
