apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.chunkCatalog.name }}
  namespace: {{ include "cse474.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.chunkCatalog.name }}
    {{- include "cse474.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.chunkCatalog.service.type }}
  selector:
    app: {{ .Values.services.chunkCatalog.name }}
  ports:
    - name: http
      port: {{ .Values.services.chunkCatalog.service.port }}
      targetPort: {{ .Values.services.chunkCatalog.containerPort }}
