apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.services.chunkCatalog.name }}-secret
  namespace: {{ include "cse474.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.chunkCatalog.name }}
    {{- include "cse474.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.services.chunkCatalog.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
