{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ include "cse474.namespace" . }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.services.chunkCatalog.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.chunkCatalog.name }}
                port:
                  number: {{ .Values.services.chunkCatalog.service.port }}
    - host: {{ .Values.services.chunkLocation.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.chunkLocation.name }}
                port:
                  number: {{ .Values.services.chunkLocation.service.port }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /storage
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.storageGateway.name }}
                port:
                  number: {{ .Values.services.storageGateway.service.port }}
          - path: /planner
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.replicationPlanner.name }}
                port:
                  number: {{ .Values.services.replicationPlanner.service.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.authService.name }}
                port:
                  number: {{ .Values.services.authService.service.port }}
          - path: /profiles
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.userProfileService.name }}
                port:
                  number: {{ .Values.services.userProfileService.service.port }}
          {{- if .Values.monitoring.enabled }}
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
          {{- end }}
{{- end }}
