apiVersion: v1
kind: ConfigMap
metadata:
  name: distributed-information-config
  namespace: cse474-prod
data:
  NODE_ENV: production
  MONGO_URI: mongodb://mongodb:27017
  MONGO_DB: distributed_information
  KAFKA_BROKERS: kafka:9092
  DEFAULT_REPLICATION_FACTOR: "3"
  DEFAULT_TARGET_NODES: storage-node-a,storage-node-b,storage-node-c
  PLANNER_INPUT_TOPICS: upload.completed,node.heartbeat.missed,integrity.failed
  OBJECT_STORAGE_ROOT: /data/objects
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_TRACES_EXPORTER: otlp
