apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pm3-services
  namespace: cse474-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: audit-log.cse474.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: audit-log-service
              port:
                number: 3025
  - host: central-logging.cse474.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: central-logging-service
              port:
                number: 3026
    - host: chunk-catalog.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chunk-catalog
                port:
                  number: 3001
    - host: chunk-location.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chunk-location
                port:
                  number: 3002
