global:
  scrape_interval: 15s

scrape_configs:
  - job_name: chunk-catalog
    metrics_path: /metrics
    static_configs:
      - targets:
          - chunk-catalog:3001

  - job_name: chunk-location
    metrics_path: /metrics
    static_configs:
      - targets:
          - chunk-location:3002
