{
 "title": "Distributed Information Services",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(service_http_requests_total)"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "avg(service_http_error_rate)" }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "service_http_request_latency_ms{quantile=\"0.95\"}"
    }
   ]
  }
 ]
}