apiVersion: v1
kind: Service
metadata:
  name: chunk-location
  namespace: cse474-prod
spec:
  type: ClusterIP
  selector:
    app: chunk-location
  ports:
    - name: http
      port: 3002
      targetPort: 3002
