namespace: cse474-prod

imageRegistry: docker.io/ahmedxdarwish
imagePullPolicy: Always

config:
  NODE_ENV: production
  MONGO_URI: mongodb://mongodb:27017
  MONGO_DB: distributed_information
  KAFKA_BROKERS: kafka:9092
  DEFAULT_REPLICATION_FACTOR: "3"
  DEFAULT_TARGET_NODES: storage-node-a,storage-node-b,storage-node-c
  PLANNER_INPUT_TOPICS: upload.completed,node.heartbeat.missed,integrity.failed
  OBJECT_STORAGE_ROOT: /data/objects
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_TRACES_EXPORTER: otlp

services:
  storageGateway:
    name: storage-gateway
    image: storage-gateway
    tag: latest
    replicas: 2
    port: 3000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  replicationPlanner:
    name: replication-planner
    image: replication-planner
    tag: latest
    replicas: 2
    port: 3000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

ingress:
  enabled: true
  host: distributed-information.local

dependencies:
  mongodb:
    enabled: true
    image: mongo:7
  kafka:
    enabled: true
    image: apache/kafka:3.7.0

monitoring:
  enabled: true
  prometheus:
    image: prom/prometheus:v2.54.1
    scrapeInterval: 15s
  grafana:
    image: grafana/grafana:11.2.0
    adminUser: admin
    adminPassword: admin
  jaeger:
    image: jaegertracing/all-in-one:1.60
  loki:
    image: grafana/loki:3.1.1
